version: '3'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
     - "7505:7505/tcp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn